# Docker compose with required environment for campaigns-service.
#
# Run with the following command: docker-compose -f docker-compose/common-environment-docker-compose.yml up -d
# Stop with the following command: docker-compose -f docker-compose/common-environment-docker-compose.yml down
version: "3"
services:
  campaigns_service:
    image: campaigns_service
    container_name: campaigns_service
    hostname: campaigns_service
    restart: always
    networks:
      - promotions
    ports:
      - "10000:10000"

  postgres:
    image: postgres:14.1
    container_name: postgres
    hostname: postgres
    restart: always
    networks:
      - promotions
    environment:
      POSTGRES_DB: "promotions"
      POSTGRES_USER: promotions_user
      POSTGRES_PASSWORD: promotions_password
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    hostname: elasticsearch
    restart: always
    networks:
      - promotions
    environment:
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"

networks:
  promotions: