# Docker compose to run environment for service-promotions and Zipkin instance.
# Run with the following command: docker-compose -f docker-compose/common-zipkin-docker-compose.yml up -d
# Stop with the following command: docker-compose -f docker-compose/common-zipkin-docker-compose.yml down
# After start open http://localhost:9411 to verify Zipkin is up and running
version: "3"
services:
  campaigns_service:
    extends:
      file: common-environment-docker-compose.yml
      service: campaigns_service
    networks:
      - promotions

  postgres:
    extends:
      file: common-environment-docker-compose.yml
      service: postgres
    networks:
      - promotions

  elasticsearch:
    extends:
      file: common-environment-docker-compose.yml
      service: elasticsearch
    networks:
      - promotions

  zipkin:
    image: openzipkin/zipkin:2
    hostname: zipkin
    container_name: zipkin
    restart: always
    networks:
      - promotions
    ports:
      - "9411:9411"

networks:
  promotions: